"""Slice -> atopile .ato codegen — ends the loop in a manufacturable BOM.

The verified blocks are authored `.ato` modules (`atopile/verified_lib.ato`); this
emits only the top-level `App` that instantiates + wires them per an orchestrator
slice. So: NL -> plan -> validated slice -> generated App.ato -> `ato build` -> BOM
of real LCSC parts. The blocks are pre-verified; codegen never invents connectivity
beyond composing typed ports.

Run:  python3 codegen.py            # generate + build the temperature-logger slice
"""
from __future__ import annotations
import re
import subprocess
from pathlib import Path

import block_contract as bc
import orchestrator as orch

ATO_DIR = Path(__file__).parent / "atopile"


def _ident(name: str) -> str:
    s = re.sub(r"[^0-9a-zA-Z_]", "_", name).lower()
    return s if not s[0].isdigit() else "n_" + s


def generate_app(slice_doc: dict, lib: dict[str, bc.BlockSpec]) -> str:
    insts = slice_doc["instances"]
    modules = list(dict.fromkeys(lib[b].atopile_module for b in insts.values()))
    L = ["# AUTO-GENERATED by codegen.py from an orchestrator slice — do not edit.",
         "import ElectricPower", "import I2C",
         f'from "verified_lib.ato" import {", ".join(modules)}', "",
         "module App:"]
    for inst, bid in insts.items():
        L.append(f"    {inst} = new {lib[bid].atopile_module}")
    L.append("")

    # strap each peripheral's address pins per the auto-assigned address
    design = bc.build_design(slice_doc, lib)
    addr = {n.block: n.address for bus in design.buses for n in bus.nodes
            if n.role == "peripheral"}
    for inst, bid in insts.items():
        cg = lib[bid].codegen
        if not cg or addr.get(inst) is None:
            continue
        base = lib[bid].ports["i2c"]["address_base"]
        off = addr[inst] - base
        L.append(f"    # {inst}: I2C address 0x{addr[inst]:02X}")
        for i, pin in enumerate(cg["address_pins"]):            # LSB-first
            rail = "hv" if (off >> i) & 1 else "lv"
            L.append(f"    {inst}.{cg['part_instance']}.{pin} ~ {inst}.power.{rail}")
    L.append("")
    for r in slice_doc.get("rails", []):
        net = _ident(r["name"])
        L.append(f"    {net} = new ElectricPower")
        if "source" in r:                      # board-edge supply: set its voltage
            v, tol = r["source"]["voltage"], r["source"]["tolerance"]
            L.append(f"    assert {net}.voltage within {v:g}V +/- {tol*100:g}%")
            L.append(f"    {net}.voltage = {v:g}V +/- {tol*100:g}%")
        else:                                  # rail driven by a block's source port
            si, sp = r["source_from"].split(".")
            L.append(f"    {si}.{sp} ~ {net}")
        for ref in r.get("sinks", []):
            inst, port = ref.split(".")
            L.append(f"    {inst}.{port} ~ {net}")
        L.append("")
    for b in slice_doc.get("buses", []):
        net = _ident(b["name"])
        L.append(f"    {net} = new I2C")
        L.append(f"    {net}.frequency = 400kHz")
        for ref in b.get("members", []):
            inst, port = ref.split(".")
            L.append(f"    {inst}.{port} ~ {net}")
        L.append("")
    return "\n".join(L) + "\n"


def build(slice_doc, lib, target="generated") -> tuple[bool, str]:
    """Write the generated App, register a build target, `ato build`, return BOM csv.

    The generated `<target>.ato` is git-ignored; the build target line appended to
    ato.yaml is runtime-only (ato.yaml's authored targets are the committed ones)."""
    (ATO_DIR / f"{target}.ato").write_text(generate_app(slice_doc, lib))
    ato_yaml = ATO_DIR / "ato.yaml"
    y = ato_yaml.read_text()
    if f"\n  {target}:" not in y:
        ato_yaml.write_text(y.rstrip() + f"\n  {target}:\n    entry: {target}.ato:App\n")
    r = subprocess.run(["ato", "build", "-b", target], cwd=ATO_DIR,
                       capture_output=True, text=True, timeout=300)
    ok = "Build successful" in (r.stdout + r.stderr)
    bom = ATO_DIR / "build" / "builds" / target / f"{target}.bom.csv"
    return ok, (bom.read_text() if ok and bom.exists() else r.stdout[-1500:])


if __name__ == "__main__":
    lib = bc.load_blocks()
    spec = "A microcontroller that logs temperature readings to memory over I2C"
    slice_doc, design, res, ok = orch.run(spec, lib, orch.HeuristicPlanner())
    print(f"SPEC: {spec}")
    print(f"validation gate: {'PASS' if ok else 'REJECT'}")
    if not ok:
        raise SystemExit("design rejected by gate; not building")
    print("\n--- generated App.ato ---")
    print(generate_app(slice_doc, lib))
    print("--- ato build ---")
    built, out = build(slice_doc, lib, target="generated")
    if built:
        print("BUILD SUCCESSFUL — manufacturable BOM:\n")
        print(out)
    else:
        print("BUILD FAILED:\n", out)
    raise SystemExit(0 if built else 1)
